name: 'Test app'

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Install pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: '9.12.1'

      - name: 'Use Node.js 22'
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: 'Install dependencies'
        run: pnpm i

      - name: 'Run Prettier'
        run: pnpm prettier

      - name: 'Run ESLint'
        run: pnpm lint

      - name: 'Run tests'
        run: pnpm test

      - name: Report results to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./reports/coverage/cobertura-coverage.xml
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
